<?php

function lbc_core_theme($existing, $type, $theme, $path) {
  return [
    'annonces_list' => [
      'template'  => 'lbc_core-annonces-list',  // Automatiquement appelé en fonction du nom du hook de thème.
      'variables' => [
        'annonces'  => NULL,
      ],
    ],
  ];
}


function annonce_form_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    $form['#attached']['library'][] = 'lbc_core/annonceform';
}

function lbc_core_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    $form['#attached']['library'][] = 'lbc_core/annonceform';
}
